# Generated by Django 5.0.4 on 2024-04-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0002_account_address_account_avatar_account_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('busowner', 'BusOwner'), ('employee', 'Employee')], default='Customer', max_length=50),
        ),
    ]
