# Generated by Django 5.0.4 on 2024-04-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0004_businfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('starting_point', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('active_time', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('estimated_duration', models.DurationField()),
                ('frequency', models.DurationField()),
                ('fare', models.FloatField()),
                ('bias', models.FloatField(default=10)),
                ('businfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.businfor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
