# Generated by Django 5.0.4 on 2024-04-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0005_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('departure_date_time', models.DateTimeField()),
                ('arrival_excepted', models.DateTimeField()),
                ('arrival_actual', models.DateTimeField()),
                ('busroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.busroute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
