# Generated by Django 5.0.4 on 2024-05-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0006_busline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('seat_code', models.CharField(max_length=10)),
                ('busline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.busline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
