# Generated by Django 5.0.4 on 2024-05-02 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0007_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('payment_time', models.DateTimeField(null=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='Offline', max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_content', models.CharField(max_length=255)),
                ('total', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('available', 'Available'), ('cancelled', 'Cancelled')], default='Available', max_length=100),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_email', models.CharField(max_length=255, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_email', models.CharField(max_length=255, null=True)),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('receive_time', models.DateTimeField(null=True)),
                ('delivery_status', models.CharField(max_length=255, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.bill')),
                ('busline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.busline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.bill')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.seat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
