# Generated by Django 5.0.4 on 2024-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0009_delivery_content_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_code',
        ),
        migrations.AddField(
            model_name='bill',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='businfor',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='busline',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='busroute',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='seat',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='Empty', max_length=255),
        ),
    ]
