# Generated by Django 5.0.4 on 2024-05-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0010_remove_seat_seat_code_bill_code_businfor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busline',
            name='arrival_actual',
            field=models.DateTimeField(null=True),
        ),
    ]
