# Generated by Django 5.0.4 on 2024-05-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0011_alter_busline_arrival_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busline',
            name='arrival_actual',
            field=models.DateTimeField(default=None),
        ),
    ]
