# Generated by Django 5.0.4 on 2024-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0014_alter_busline_arrival_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
