# Generated by Django 5.0.4 on 2024-05-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0015_alter_account_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('busline', 'code')},
        ),
    ]
