# Generated by Django 5.0.4 on 2024-05-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0016_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.bill'),
        ),
    ]
