# Generated by Django 5.0.4 on 2024-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0019_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='businfor',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='busline',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='Empty', max_length=255, unique=True),
        ),
    ]
