# Generated by Django 5.0.4 on 2024-05-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0021_alter_businfor_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businfor',
            old_name='account',
            new_name='account_id',
        ),
    ]
