# Generated by Django 5.0.4 on 2024-05-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0022_rename_account_businfor_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businfor',
            old_name='account_id',
            new_name='account',
        ),
    ]
