# Generated by Django 5.0.4 on 2024-05-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0023_rename_account_id_businfor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='estimated_duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
    ]
