# Generated by Django 5.0.4 on 2024-05-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0024_alter_busroute_estimated_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
