# Generated by Django 5.0.4 on 2024-05-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0025_remove_bill_payment_status_bill_payment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='busline',
        ),
        migrations.AddField(
            model_name='delivery',
            name='businfor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.businfor'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.bill', unique=True),
        ),
    ]
