# Generated by Django 5.0.4 on 2024-05-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0026_remove_delivery_busline_delivery_businfor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
