# Generated by Django 5.0.4 on 2024-05-25 05:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0027_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Empty', max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_email', models.CharField(max_length=255, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_email', models.CharField(max_length=255, null=True)),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('receive_time', models.DateTimeField(null=True)),
                ('delivery_status', models.BooleanField(default=False)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.bill', unique=True)),
                ('businfor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.businfor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
