# Generated by Django 5.0.4 on 2024-05-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0028_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='businfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.businfor'),
        ),
    ]
