# Generated by Django 5.0.4 on 2024-05-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0029_alter_delivery_businfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
