# Generated by Django 5.0.4 on 2024-05-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buslinesapp', '0030_delivery_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buslinesapp.bill', unique=True),
        ),
    ]
